run.java=25+
build.java=25+
dependencies=dev.tamboui:tamboui-core:LATEST,dev.tamboui:tamboui-tui:LATEST,dev.tamboui:tamboui-toolkit:LATEST,dev.tamboui:tamboui-widgets:LATEST,dev.tamboui:tamboui-annotations:LATEST,dev.tamboui:tamboui-css:LATEST,dev.tamboui:tamboui-tfx:LATEST,dev.tamboui:tamboui-tfx-tui:LATEST,dev.tamboui:tamboui-tfx-toolkit:LATEST,dev.tamboui:tamboui-jline3-backend:LATEST
sources=snippets/**/*.java
runtimeoption=--enable-native-access=ALL-UNNAMED